title: Diario IA
description: Un blog profesional con IA y Jekyll
baseurl: ""
url: "https://tuusuario.github.io/diario-ia"
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 5
paginate_path: "/page:num/"
