# Configuración para GitHub Pages
theme: jekyll-theme-minimal
title: Mi Diario de IA
description: Un blog personal sobre inteligencia artificial, machine learning y tecnología
show_downloads: false
google_analytics: # Añade tu código de Google Analytics aquí

# Configuración SEO
lang: es
author: Tu Nombre

# Plugins recomendados (se instalan automáticamente en GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclusiones
exclude:
  - README.md
  - LICENSE
  - .gitignore
