title: Diario IA Profesional
description: Un blog profesional con IA y diseño Copilot
baseurl: ""
url: "https://tuusuario.github.io/diario-ia"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: "/page:num/"
