name: Generar entrada IA

on:
  workflow_dispatch:
    inputs:
      titulo:
        description: 'Título de la entrada'
        required: true
      contenido:
        description: 'Contenido generado por IA'
        required: true

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Crear entrada
        run: |
          mkdir -p _posts
          FECHA=$(date +%Y-%m-%d)
          ARCHIVO="_posts/$FECHA-${{ github.event.inputs.titulo | toLower | gsub(' ', '-') }}.md"
          echo "---" > $ARCHIVO
          echo "layout: default" >> $ARCHIVO
          echo "title: \"${{ github.event.inputs.titulo }}\"" >> $ARCHIVO
          echo "date: $FECHA" >> $ARCHIVO
          echo "---" >> $ARCHIVO
          echo "${{ github.event.inputs.contenido }}" >> $ARCHIVO

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _posts/
          git commit -m "Nueva entrada generada por IA"
          git push
