name: Generar entrada IA

on:
  workflow_dispatch:
    inputs:
      titulo:
        description: 'Título de la entrada'
        required: true
      contenido:
        description: 'Contenido de la entrada'
        required: true

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crear entrada
        run: |
          FECHA=$(date +'%Y-%m-%d')
          NOMBRE="${{ github.event.inputs.titulo }}"
          ARCHIVO="_posts/$FECHA-${NOMBRE// /-}.md"
          echo "---" > $ARCHIVO
          echo "layout: post" >> $ARCHIVO
          echo "title: \"${NOMBRE}\"" >> $ARCHIVO
          echo "date: $FECHA" >> $ARCHIVO
          echo "categories: [ia]" >> $ARCHIVO
          echo "---" >> $ARCHIVO
          echo "${{ github.event.inputs.contenido }}" >> $ARCHIVO

      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _posts/
          git commit -m "Nueva entrada generada por IA"
          git push
