name: Generar entrada IA

on:
  workflow_dispatch:
    inputs:
      titulo:
        description: 'Título de la entrada'
        required: true
      contenido:
        description: 'Contenido de la entrada'
        required: true

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Crear entrada
        run: |
          mkdir -p _posts
          fecha=$(date +'%Y-%m-%d')
          nombre="${fecha}-${{ github.event.inputs.titulo | slugify }}.md"
          echo "---" > _posts/$nombre
          echo "layout: default" >> _posts/$nombre
          echo "title: \"${{ github.event.inputs.titulo }}\"" >> _posts/$nombre
          echo "date: $fecha" >> _posts/$nombre
          echo "categories: [ia]" >> _posts/$nombre
          echo "---" >> _posts/$nombre
          echo "${{ github.event.inputs.contenido }}" >> _posts/$nombre
      - name: Commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts/
          git commit -m "Nueva entrada generada por IA"
          git push
