name: Generar entrada IA

on:
  workflow_dispatch:
    inputs:
      titulo:
        description: 'Título de la entrada'
        required: true
      contenido:
        description: 'Contenido de la entrada'
        required: true

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Crear entrada
        run: |
          FECHA=$(date +'%Y-%m-%d')
          SLUG=$(echo "${{ github.event.inputs.titulo }}" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g' | tr -cd '[:alnum:]-')
          ARCHIVO="_posts/$FECHA-$SLUG.md"
          echo "---" > $ARCHIVO
          echo "layout: post" >> $ARCHIVO
          echo "title: \"${{ github.event.inputs.titulo }}\"" >> $ARCHIVO
          echo "date: $FECHA" >> $ARCHIVO
          echo "categories: [IA]" >> $ARCHIVO
          echo "---" >> $ARCHIVO
          echo "${{ github.event.inputs.contenido }}" >> $ARCHIVO

      - name: Subir cambios
        run: |
          git add _posts/
          git commit -m "Nueva entrada: ${{ github.event.inputs.titulo }}"
          git push
